name: Deploy to Dev on merge
'on':
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployArgs:
        description: What to deploy
        type: choice
        options:
          - --except storage
          - --only hosting
          - --only functions
          - --only firestore
          - --only storage
        required: false
        default:
jobs:
  build:
    if: false
    name: Build
    runs-on: ubuntu-latest
    environment: development
    env:
      GOOGLE_CONFIG: ${{ secrets.GOOGLE_CONFIG }}
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
      - run: echo '${{ github.event.inputs.deployArgs }}'
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Set Google Configs
        run: echo $GOOGLE_CONFIG > './src/google/config.env.json'
      - name: Set Firebase Config
        run: echo $FIREBASE_CONFIG > './src/firebase/config.env.json'
      - name: Build
        run: npx quasar build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    #needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy ${{ github.event.inputs.deployArgs }}
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENQUEUECARD }}
          PROJECT_ID: development
